// Generated by buoy tokens
// Import and spread into your tailwind.config.js theme.extend

module.exports = {
  colors: {},
  spacing: {
    "size-1": "8px"
},
  fontSize: {},
  borderRadius: {
    "sm": "4px"
},
};
